name: chess_logic
description: A Dart package for chess logic, including move generation, validation, and game state management.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.7
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
